### ISSUE TITLE
cannot find weeSAM_coverage.r

### ISSUE THREAD

**Issue by krepsen** [josephhughes/Sequence-manipulation#1]
Probably a stupid question, but I cannot find the weeSAM_coverage.r
I get the stat output, but not the graph - I'm getting the following error message:
`weeSAM_coverage.r tmp_depth.txt MA2_plot.pngCan't exec "weeSAM_coverage.r": No such file or directory at /usr/bin/weeSAMv1.4 line 140.`
Downloaded *.pl and placed in path

**Comment by josephhughes** [comment]
Added here:
https://github.com/josephhughes/Sequence-manipulation/blob/master/weeSAM_coverage.r
